{% set name = "skl2onnx" %}
{% set build_version = "1.13" %}


package:
  name: {{ name|lower }}
  version: {{ build_version }}

source:
  git_url: https://github.com/onnx/sklearn-onnx.git
  git_rev: {{ build_version }}
  patches:
    - 0001-Update-pin-of-scikit-learn.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six {{ six }}
    - numpy {{ numpy }}
    - scipy {{ scipy }}
    - protobuf {{ protobuf }}
    - onnx {{ onnx }}
    - scikit-learn >=0.19
    - onnxconverter-common {{ onnxconverter_common }}
    - packaging

test:
  imports:
    - skl2onnx
  commands:
    - pip check

about:
  home: https://github.com/onnx/sklearn-onnx
  summary: Convert scikit-learn models and pipelines to ONNX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
